version: '1'
services:
  redis:
    image: redis/redis-stack
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: ./docker/DockerFile.web
    volumes:
      - .:/app
    ports:
      - 5010:5000
    environment:
      - FLASK_APP=app
    depends_on:
      - redis


  celery:
    build:
      context: .
      dockerfile: ./docker/DockerFile.celery
    volumes:
      - .:/app
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
